name: sandbox
description: >
  Play and test mason templates
version: 0.1.0
# homepage: https://github.com/felangel/mason
# repository: https://github.com/felangel/mason
# issue_tracker: https://github.com/felangel/mason/issues
documentation: https://docs.brickhub.dev
topics: [mason, template, generator]

environment:
  sdk: ">=3.10.0 <4.0.0"

# dependencies:
dev_dependencies:
  mason: ^0.1.2
  build_runner: ^2.4.12
  build_verify: ^3.1.0
  build_version: ^2.1.1
  json_serializable: ^6.8.0
  mocktail: ^1.0.4
  test: ^1.25.8
