name: sandbox
description: >
  Play and test mason templates
version: 0.1.0

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  bloc: ^9.0.0
  bloc_concurrency: ^0.3.0
  flutter_bloc: ^9.0.0
  meta: ^1.16.0
  logging: ^1.3.0
  drift: ^2.15.0
  drift_dev: ^2.15.0
  path: ^1.9.0
  path_provider: ^2.1.3
  rxdart: ^0.27.7
  sqlite3_flutter_libs: ^0.5.0
  freezed_annotation: ^3.1.0
  collection: ^1.19.1

dev_dependencies:
  json_serializable: ^6.9.0
  freezed: ^3.1.0
  mason: ^0.1.2
  build_runner: ^2.4.12
  build_verify: ^3.1.0
  build_version: ^2.1.1
  mocktail: ^1.0.4
  test: ^1.25.8
